language: python
python:
    - "3.4"
    - "3.5"
install:
  - pip install -e .
  - pip install -r tests/requirements.txt
script: pytest --cov=voidpp_tools --cov-report term --cov-report xml --cov-report annotate
after_success:
  coveralls
